# Generated by Django 4.0.5 on 2022-06-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('bio', models.CharField(max_length=30)),
                ('profile_image', models.ImageField(default='brian', upload_to='image/')),
            ],
        ),
    ]
