# Generated by Django 4.0.5 on 2022-06-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_likes_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_image', models.ImageField(default='brian', upload_to='image/')),
                ('image_name', models.CharField(max_length=60)),
                ('image_caption', models.TextField()),
                ('likes', models.ManyToManyField(to='insta.likes')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.profile')),
            ],
        ),
    ]
