# Generated by Django 4.0.5 on 2022-06-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='comments',
            field=models.ManyToManyField(to='insta.comments'),
        ),
    ]
