# Generated by Django 4.0.5 on 2022-06-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_images_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='profile',
        ),
    ]
